### PR TITLE
Add configurable email

### LINKED ISSUE #13: Allow different email receivers per form

### PR DESCRIPTION
**Pull request by chhantyal**
Fixes #13

### CODE REVIEW

**Comment by MarkusH** [comment]
Could you add a testcase in https://github.com/MarkusH/django-dynamic-forms/blob/develop/tests/test_actions.py#L82

**Comment by chhantyal** [comment]
Added. I hope now coveralls won't say I decreased coverage.

**Comment by MarkusH** [comment]
Perfect, thanks. I'll have a look and merge it.

**Comment by MarkusH** [comment]
Merged with slight changes and doc updates in dc99fd96ebec80597767287504b7b2a6d5c7207f. Thanks!

**Comment by chhantyal** [comment]
That's great. +1:

**Pull request closed without merging**
