### PR TITLE
change app name

### PR DESCRIPTION
**Pull request by chhantyal**

### CODE REVIEW

**Comment by chhantyal** [comment]
Something is wrong with CI

**Comment by MarkusH** [comment]
Yes, see #19

**Comment by MarkusH** [comment]
This change requires updates to the .po files, too.

**Comment by MarkusH** [comment]
Tests should pass again. Could you rebase onto current master.

**Comment by chhantyal** [comment]
You meant `develop` branch? ;)

I ran makemessages command, there are far too many changes, thus sent without it.

So what would be better - run makemessages or update line in .po files?

**Comment by MarkusH** [comment]
Yes, develop. ;)

I'll do the .po/.mo stuff myself. Thanks!

**Comment by MarkusH** [comment]
Merged in b1e5e21f91cb6dfc28b41d21b9f3fe667dfc578e. Thanks!

**Pull request closed without merging**
